### ISSUE TITLE
[FEATURE] A super event and its sub-events need to belong to the same Rokwire Group.

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#754]
**Is your feature request related to a problem? Please describe.**
Currently, all published events are visible when users search for adding sub-events. This can create confusion since a user won't be able to view an event that they don't have access to (if they don't have admin membership in the group that created the event).

**Describe the solution you'd like**
All the sub-events of a super event need to belong to the same Rokwire group as that of the super event and the user should be an admin of the same group. Only such events should be visible In the auto-complete text box.

**Describe alternatives you've considered**
No other alternatives are considered at this point.

**Additional context**

Epic: #745

**Comment by bingzhang** [comment]
@AnubhavG1999 any update on this task? 
cc @sandeep-ps @hannah-ischool

**Comment by AnubhavG1999** [comment]
@bingzhang I haven't really looked at this issue much, but (https://github.com/rokwire/events-manager/pull/503) should have a map and filter function that could be useful with changes. This pull request was originally meant to filter out subevents and superevents so that they do not show up when a user is trying to add an event as a sub event. The map and filter functions can probably be refactored.

**Comment by sandeep-ps** [comment]
@bingzhang, I'm reopening this issue based on today's chat. Please see the issue description for more details. Thanks.

**Comment by sandeep-ps** [comment]
I'm closing this issue based on today's discussion with @kpecknold. We couldn't identify a business use case for this task.
